### PR TITLE
try fixing widgets rendering

### PR DESCRIPTION
**Pull request by OriolAbril**
Adds some extra javascript to ensure widgets are rendered correctly
as static elements even without access to a python kernel.

Also does some minor doc config updates, mainly making the light theme the default.

### CODE REVIEW

**Comment by OriolAbril** [comment]
looks basically the same now 🤔

**Comment by aloctavodia** [comment]
Yep, I am not able  to spot any difference

**Comment by OriolAbril** [comment]
Let's see how it looks now. It turns out ipywidgets adds one of these red broken chain icons _per element that should be connected to a kernel but isn't_. I guess it is informative, but a bit too much. I added an extra css rule to remove that.

**Comment by aloctavodia** [comment]
Thanks, this looks much better!

**Pull request merged**
